import React, { createContext, useContext, useState, useCallback, ReactNode } from 'react';


type Language = 'tr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  tr: {
    // Navigation
    'nav.solutions': 'Çözümler',
    'nav.readyLines': 'Hazır Hatlar',
    'nav.singleMachines': 'Tekil Makineler',
    'nav.customProjects': 'Özel Projeler',
    'nav.services': 'Hizmetler',
    'nav.references': 'Referanslar',
    'nav.corporate': 'Kurumsal',
    'nav.blog': 'Blog / Rehber',
    'nav.contact': 'İletişim',
    
    // Hero
    'hero.label': 'ENDÜSTRİYEL ÇÖZÜMLER',
    'hero.line1': 'Üretim Projeniz İçin',
    'hero.line2': 'Teklif Alın',
    'hero.description': 'Gıda üretiminden sektör bağımsız projelere kadar, ihtiyaca göre tasarlanan ve sahada çalışan sistemler kuruyoruz.',
    'hero.cta': 'Proje Detaylarını Gönderin',
    'hero.learnMore': 'Çözümleri İncele',
    'hero.weSupport': 'DESTEKLENEN ALANLAR',
    'hero.support.readyLines': 'Hazır Üretim Hatları',
    'hero.support.readyLines.desc': 'Salça, sos, domates işleme hatları',
    'hero.support.singleMachines': 'Tekil Makineler',
    'hero.support.singleMachines.desc': 'Süt prosesi, dolum & paketleme',
    'hero.support.customProjects': 'Özel Projeler',
    'hero.support.customProjects.desc': 'Sektör bağımsız anahtar teslim çözümler',
    'hero.support.technical': 'Teknik Koordinasyon',
    'hero.support.technical.desc': 'Mühendislik, kurulum, devreye alma',
    'hero.feature.turnkey': 'Anahtar Teslim',
    'hero.feature.sourcing': 'Esnek Tedarik',
    'hero.feature.multiSector': 'Çoklu Sektör',
    'hero.feature.proposals': 'Yapısal Teklifler',
    
    // Hero Slides
    'hero.slide2.label': 'ONLİNE KONFİGÜRATÖR',
    'hero.slide2.line1': 'Üretim Hattınızı',
    'hero.slide2.line2': 'Online Konfigüre Edin',
    'hero.slide2.description': 'Salça, sos, süt ve dolum hatları için interaktif konfigüratörümüzle ihtiyacınıza uygun hattı oluşturun.',
    'hero.slide2.cta': 'Konfigüratörü Aç',
    'hero.slide2.secondary': 'Çözümleri İncele',
    'hero.slide3.label': 'GLOBAL REFERANSLAR',
    'hero.slide3.line1': '30+ Ülkede',
    'hero.slide3.line2': 'Üretim Çözümleri',
    'hero.slide3.description': 'Dünya genelinde tamamlanmış projeler ve güvenilir iş ortaklıkları ile sektörde fark yaratıyoruz.',
    'hero.slide3.cta': 'Referansları Gör',
    'hero.slide3.secondary': 'Bizi Tanıyın',
    
    // Quick Cards
    'card.readyLine.title': 'Hazır Hat Seç',
    'card.readyLine.desc': 'Salça, domates, mayonez, ketçap ve sos üretim hatları',
    'card.singleMachine.title': 'Tekil Makine Seç',
    'card.singleMachine.desc': 'Süt prosesi, dolum ve paketleme makineleri',
    'card.customProject.title': 'Özel Proje Başlat',
    'card.customProject.desc': 'Sektör bağımsız anahtar teslim çözümler',
    
    // Process Steps
    'process.label': 'SÜREÇ',
    'process.title': 'Nasıl Çalışıyoruz?',
    'process.step1': 'Analiz',
    'process.step2': 'Konsept',
    'process.step3': 'Tedarik',
    'process.step4': 'Kurulum',
    'process.step5': 'Devreye Alma',
    'process.step6': 'Büyüme',
    
    // CTA
    'cta.label': 'BAŞLAYIN',
    'cta.title': 'Projenizi 2 dakikada tarif edin',
    'cta.subtitle': 'Ücretsiz ön değerlendirme ve teknik danışmanlık',
    'cta.button': 'Hızlı Teklif Al',
    
    // Solutions
    'solutions.title': 'Çözümlerimiz',
    'solutions.turnkey.title': 'Anahtar Teslim Tesis Kurulumu',
    'solutions.turnkey.desc': 'Gıda tesisleri, süt & süt ürünleri, dolum & paketleme tesisleri',
    'solutions.engineering.title': 'Üretim Hattı Tasarımı & Mühendislik',
    'solutions.engineering.desc': 'Proses tasarımı, kapasite planlama, ekipman listeleri, yerleşim planları',
    'solutions.installation.title': 'Kurulum, Devreye Alma & Eğitim',
    'solutions.installation.desc': 'Saha koordinasyonu, commissioning, operatör eğitimi',
    
    // Ready Lines
    'readyLines.title': 'Hazır Hatlar',
    'readyLines.tomato.title': 'Salça & Domates İşleme Hatları',
    'readyLines.tomato.desc': 'Modüler, ölçeklenebilir üretim sistemleri',
    'readyLines.sauce.title': 'Mayonez, Ketçap & Sos Üretim Hatları',
    'readyLines.sauce.desc': 'Profesyonel, yüksek kapasiteli hat çözümleri',
    
    // Single Machines
    'singleMachines.title': 'Tekil Makineler',
    'singleMachines.dairy.title': 'Süt Prosesi Makineleri',
    'singleMachines.dairy.desc': 'Homojenizatör, separatör, pastörizatör ve daha fazlası',
    'singleMachines.filling.title': 'Dolum & Paketleme Makineleri',
    'singleMachines.filling.desc': 'Dolum, kapak kapama, etiketleme sistemleri',
    
    // Custom Projects
    'customProjects.title': 'Özel Projeler',
    'customProjects.hero': 'Katalogla sınırlı değiliz',
    'customProjects.heroDesc': 'Projenin ihtiyacını tanımlar, çalışan sistemi kurarız.',
    
    // Services
    'services.title': 'Hizmetlerimiz',
    'services.engineering': 'Proje & Mühendislik',
    'services.manufacturer': 'Üretici Organizasyonu',
    'services.tracking': 'Üretim Takibi & Test',
    'services.logistics': 'Lojistik',
    'services.installation': 'Kurulum & Devreye Alma',
    'services.training': 'Eğitim',
    'services.support': 'Teknik Servis & Yedek Parça',
    
    // References
    'references.title': 'Referanslarımız',
    'references.food': 'Gıda Projeleri',
    'references.dairy': 'Süt Projeleri',
    'references.custom': 'Özel Projeler',
    
    // Corporate
    'corporate.title': 'Kurumsal',
    'corporate.about': 'Hakkımızda',
    'corporate.vision': 'Vizyon & Misyon',
    'corporate.whyTurkey': 'Neden Türkiye Üreticileri?',
    'corporate.team': 'Ekibimiz',
    
    // Blog
    'blog.title': 'Blog & Rehber',
    
    // Contact
    'contact.title': 'İletişim',
    'contact.form.name': 'Ad Soyad',
    'contact.form.email': 'E-posta',
    'contact.form.phone': 'Telefon',
    'contact.form.company': 'Firma Adı',
    'contact.form.message': 'Mesajınız',
    'contact.form.submit': 'Gönder',
    'contact.whatsapp': 'WhatsApp ile İletişim',
    
    // Footer
    'footer.rights': 'Tüm hakları saklıdır.',
    'footer.quickLinks': 'Hızlı Bağlantılar',
    'footer.contact': 'İletişim Bilgileri',
    
    // Line Builder
    'lineBuilder.title': 'Kendi Dolum Hattınızı Oluşturun',
    'lineBuilder.subtitle': 'Ürün tipinize, kapasitenize ve ambalaj tercihinize göre hat yapılandırmanızı oluşturun.',
    'lineBuilder.step1': 'Ürün Tipi',
    'lineBuilder.step2': 'Kapasite',
    'lineBuilder.step3': 'Ambalaj Tipi',
    'lineBuilder.step4volume': 'Ambalaj Hacmi',
    'lineBuilder.step5': 'Hat Ekipmanları',
    'lineBuilder.step1.desc': 'Dolum yapılacak ürünün tipini seçin.',
    'lineBuilder.step2.desc': 'Saatlik üretim kapasitenizi belirleyin.',
    'lineBuilder.step3.desc': 'Kullanacağınız ambalaj tipini seçin.',
    'lineBuilder.step4volume.desc': 'Dolum yapılacak ambalajın hacmini seçin.',
    'lineBuilder.step5.desc': 'Önerilen ekipmanlar otomatik seçildi. İhtiyacınıza göre ekleyip çıkarabilirsiniz.',
    'lineBuilder.summary': 'Hat Özeti',
    'lineBuilder.getQuote': 'Bu Hat İçin Teklif İste',
    'lineBuilder.reset': 'Sıfırla',
    'lineBuilder.quote.contactTitle': 'İletişim Bilgileriniz',
    'lineBuilder.quote.note': 'Ek Not / Özel İstekler',
    'lineBuilder.quote.submit': 'Teklif Talebini Gönder',
    'lineBuilder.quote.sent': 'Teklif Talebiniz Hazırlandı!',
    'lineBuilder.quote.sentDesc': 'E-posta uygulamanız açılacak. Mesajı göndererek teknik ofisimize ulaşabilirsiniz.',
    'lineBuilder.product.liquid': 'Sıvı',
    'lineBuilder.product.semiFluid': 'Yarı Akışkan',
    'lineBuilder.product.viscous': 'Viskoz',
    'lineBuilder.product.powder': 'Toz / Granül',
    'lineBuilder.product.liquid.desc': 'Su, süt, meyve suyu',
    'lineBuilder.product.semi-fluid.desc': 'Yoğurt, bal, reçel',
    'lineBuilder.product.viscous.desc': 'Salça, ketçap, mayonez',
    'lineBuilder.product.powder.desc': 'Toz gıda, baharat, granül',
    'lineBuilder.capacity.small': 'Küçük',
    'lineBuilder.capacity.medium': 'Orta',
    'lineBuilder.capacity.large': 'Büyük',
    'lineBuilder.capacity.industrial': 'Endüstriyel',
    'lineBuilder.capacity.small.desc': '500–2.000 adet/saat',
    'lineBuilder.capacity.medium.desc': '2.000–5.000 adet/saat',
    'lineBuilder.capacity.large.desc': '5.000–10.000 adet/saat',
    'lineBuilder.capacity.industrial.desc': '10.000+ adet/saat',
    'lineBuilder.packaging.glass': 'Cam Şişe',
    'lineBuilder.packaging.pet': 'Pet Şişe',
    'lineBuilder.packaging.tin': 'Teneke Kutu',
    'lineBuilder.packaging.pouch': 'Pouch / Doypack',
    'lineBuilder.packaging.jar': 'Kavanoz',
    'lineBuilder.packaging.ibc': 'Bidon / IBC',
    'lineBuilder.equipment.filler': 'Dolum Makinesi',
    'lineBuilder.equipment.capper': 'Kapak Kapama',
    'lineBuilder.equipment.labeler': 'Etiketleme',
    'lineBuilder.equipment.shrink': 'Shrink Ambalaj',
    'lineBuilder.equipment.conveyor': 'Konveyör Sistemi',
    'lineBuilder.equipment.uv': 'UV / Sterilizasyon',
    'lineBuilder.equipment.accumulation': 'Birikim Masası',

    // Configurator Slider
    'config.slide1.label': 'KONFİGÜRATÖR',
    'config.slide1.line1': 'Üretim Hattınızı',
    'config.slide1.line2': 'Online Konfigüre Edin',
    'config.slide1.description': 'Salça, sos, süt prosesi veya dolum & paketleme — ihtiyacınıza uygun konfigürasyonu oluşturun ve teklif alın.',
    'config.slide1.cta': 'Aşağıdan Başlayın',
    'config.slide1.secondary': 'Çözümleri İncele',
    'config.slide2.label': 'SALÇA & DOMATES',
    'config.slide2.line1': 'MACLINE Serisi',
    'config.slide2.line2': 'Domates İşleme Hatları',
    'config.slide2.description': 'Brix hesaplayıcı ve detaylı karşılaştırma tablosu ile size en uygun paketi bulun.',
    'config.slide2.cta': 'Salça Konfigüratörü',
    'config.slide2.secondary': 'Hazır Hatlar',
    'config.slide3.label': 'SOS & SÜT PROSESİ',
    'config.slide3.line1': 'Sos Hatları &',
    'config.slide3.line2': 'Süt İşleme Sistemleri',
    'config.slide3.description': 'Mayonez, ketçap, sos üretim hatları ve süt prosesi ekipmanlarını tek yerden konfigüre edin.',
    'config.slide3.cta': 'Sos Konfigüratörü',
    'config.slide3.secondary': 'Süt Prosesi',
    'config.support.label': 'KONFİGÜRASYON ALANLARI',
    'config.support.tomato': 'Salça & Domates',
    'config.support.tomato.desc': 'MACLINE serisi domates işleme hatları',
    'config.support.sauce': 'Sos Hatları',
    'config.support.sauce.desc': 'Mayonez, ketçap & sos üretim sistemleri',
    'config.support.dairy': 'Süt Prosesi',
    'config.support.dairy.desc': 'Pastörizasyon, homojenizasyon ekipmanları',
    'config.support.filling': 'Dolum & Paketleme',
    'config.support.filling.desc': 'İnteraktif hat oluşturucu ile dolum hattı',

    // Common
    'common.explore': 'İncele',
    'common.learnMore': 'Detaylı Bilgi',
    'common.getQuote': 'Teklif Al',
    'common.viewAll': 'Tümünü Gör',
    'common.back': 'Geri',
    'common.compare': 'Karşılaştır',

    // Sunum / Presentation Landing
    'sunum.nav': 'Sunum',
    'sunum.hero.eyebrow': 'ENDÜSTRİYEL PROJE GELİŞTİRME',
    'sunum.hero.title1': 'Üretime başlamak',
    'sunum.hero.title2': 'zor değil.',
    'sunum.hero.title3': 'Sen fikrini söyle,',
    'sunum.hero.title4': 'biz sistemini kurarız.',
    'sunum.hero.desc': 'ProcessTürk; yatırım fikrini uygulanabilir üretim sistemine dönüştüren, anahtar teslim tesisler ve makine tedarik koordinasyonu sunan uluslararası bir endüstriyel çözüm markasıdır.',
    'sunum.hero.cta': 'Projenizi Anlatın',
    'sunum.hero.secondary': 'Hizmet Alanları',
    'sunum.hero.tagBadge': 'Türkiye • Afrika • Körfez • Orta Doğu',

    'sunum.positioning.eyebrow': 'KONUMLANDIRMA',
    'sunum.positioning.title': 'Sadece makine değil,',
    'sunum.positioning.titleAccent': 'çalışan bir üretim sistemi.',
    'sunum.positioning.desc': 'Endüstriyel yatırım yalnızca makine satın almak değildir. Çalışan bir üretim sistemi kurmaktır. Rolümüz; yatırımcının neyin kurulacağını, hangi ekipmanlara ihtiyaç olduğunu ve fikirden üretime geçişin nasıl olacağını netleştirmektir.',

    'sunum.approach.eyebrow': 'YAKLAŞIMIMIZ',
    'sunum.approach.title': 'Fikirden üretime,',
    'sunum.approach.titleAccent': 'tek bir koordinasyon.',
    'sunum.approach.desc': 'Müşteri farklı üreticiler ve teknik ekiplerle ayrı ayrı uğraşmak zorunda kalmaz. ProcessTürk tüm süreci tek bir proje yapısı altında yönetir.',
    'sunum.approach.card1.title': 'Teknik Yapılandırma',
    'sunum.approach.card1.desc': 'Ürün, kapasite ve otomasyon ihtiyacına göre hat tasarımı.',
    'sunum.approach.card2.title': 'Makine Tedariki',
    'sunum.approach.card2.desc': 'Doğrulanmış üreticiler arasından karşılaştırmalı tedarik.',
    'sunum.approach.card3.title': 'Proses Planlaması',
    'sunum.approach.card3.desc': 'Hammadde girişinden paketlemeye kadar akış kurgusu.',
    'sunum.approach.card4.title': 'Kurulum Koordinasyonu',
    'sunum.approach.card4.desc': 'Sahada montaj, devreye alma ve test süreçleri.',
    'sunum.approach.card5.title': 'Başlangıç Desteği',
    'sunum.approach.card5.desc': 'Operatör eğitimi ve üretim başlangıcı koordinasyonu.',

    'sunum.process.eyebrow': 'PROSES AKIŞI',
    'sunum.process.title': 'Tek bir sistem,',
    'sunum.process.titleAccent': 'akışı belirlenmiş.',
    'sunum.process.step1': 'Hammadde Hazırlığı',
    'sunum.process.step2': 'Karıştırma & Pişirme',
    'sunum.process.step3': 'Bekletme Tankı',
    'sunum.process.step4': 'Dolum',
    'sunum.process.step5': 'Kapak Kapama',
    'sunum.process.step6': 'Etiketleme',
    'sunum.process.step7': 'Final Paketleme',

    'sunum.numbers.eyebrow': 'KAPASİTE',
    'sunum.numbers.title': 'Ölçeklenebilir',
    'sunum.numbers.titleAccent': 'üretim altyapısı.',
    'sunum.numbers.stat1Value': '1.500 kg/h',
    'sunum.numbers.stat1Label': 'Maksimum saatlik üretim',
    'sunum.numbers.stat1Desc': 'Reçete, viskozite ve dolum formatına göre yapılandırılabilir kapasite.',
    'sunum.numbers.stat2Value': '8–12 hafta',
    'sunum.numbers.stat2Label': 'Tipik teslim süresi',
    'sunum.numbers.stat2Desc': 'Konfigürasyon ve üretici koşullarına göre değişkenlik gösterir.',
    'sunum.numbers.stat3Value': '3 seviye',
    'sunum.numbers.stat3Label': 'Otomasyon esnekliği',
    'sunum.numbers.stat3Desc': 'Entry, Standard ve Advanced konfigürasyonlar.',

    'sunum.services.eyebrow': 'HİZMET ALANLARI',
    'sunum.services.title': 'Endüstriyel kapsam,',
    'sunum.services.titleAccent': 'sektör bağımsız.',
    'sunum.services.coreLabel': 'Temel Endüstriyel Alanlar',
    'sunum.services.additionalLabel': 'Ek Proje Alanları',
    'sunum.services.core1': 'Sos, Mayonez & Ketçap Hatları',
    'sunum.services.core2': 'Salça & Domates İşleme',
    'sunum.services.core3': 'Süt Prosesi Hatları',
    'sunum.services.core4': 'Dolum & Paketleme Sistemleri',
    'sunum.services.core5': 'Soğuk Depo Çözümleri',
    'sunum.services.core6': 'Anahtar Teslim Gıda Tesisleri',
    'sunum.services.core7': 'Özel Endüstriyel Projeler',
    'sunum.services.add1': 'Bal İşleme Tesisi',
    'sunum.services.add2': 'Bulyon Üretim Tesisi',
    'sunum.services.add3': 'Tuz İşleme & Paketleme',
    'sunum.services.add4': 'Küp Şeker Üretim Tesisi',
    'sunum.services.add5': 'Yumurta Üretim Tesisi',
    'sunum.services.add6': 'Sabun, Deterjan & Çamaşır Suyu',
    'sunum.services.add7': 'Plastik Geri Dönüşüm Hatları',
    'sunum.services.add8': 'İnşaat Malzemesi Tesisleri',

    'sunum.value.eyebrow': 'NEDEN PROCESSTÜRK',
    'sunum.value.title': 'Teknik doğruluk,',
    'sunum.value.titleAccent': 'ticari uygulanabilirlik.',
    'sunum.value.card1.title': 'Tek Noktadan Koordinasyon',
    'sunum.value.card1.desc': 'Üreticiler ve teknik ekiplerle ayrı ayrı uğraşmak zorunda kalmazsınız.',
    'sunum.value.card2.title': 'Uygulanabilir Yaklaşım',
    'sunum.value.card2.desc': 'Yalnızca ürün listesi değil, çalışabilir bir üretim sistemi kurarız.',
    'sunum.value.card3.title': 'Bütçeye Göre Yapılandırma',
    'sunum.value.card3.desc': 'Entry, Standard veya Advanced — yatırım bütçenize göre seviye.',
    'sunum.value.card4.title': 'Uluslararası Deneyim',
    'sunum.value.card4.desc': 'Türkiye, Afrika, Körfez ve Orta Doğu pazarlarında proje deneyimi.',
    'sunum.value.card5.title': 'Teknik + Ticari Bakış',
    'sunum.value.card5.desc': 'Mühendislik kadar geri dönüş, operasyon ve ticari uygulanabilirlik.',
    'sunum.value.card6.title': 'Ölçeklenebilir Sistem',
    'sunum.value.card6.desc': 'Küçük başlayıp ileride kapasite ve otomasyonu artırın.',

    'sunum.config.eyebrow': 'KONFİGÜRASYON SEVİYELERİ',
    'sunum.config.title': 'Doğru makine,',
    'sunum.config.titleAccent': 'doğru yatırım.',
    'sunum.config.entry.label': 'Entry',
    'sunum.config.entry.tag': 'Başlangıç',
    'sunum.config.entry.desc': 'Daha düşük yatırım bütçesine uygun, yarı otomatik çözüm. Temel üretim fonksiyonları karşılanır.',
    'sunum.config.entry.b1': 'Yarı otomatik konfigürasyon',
    'sunum.config.entry.b2': 'Daha düşük yatırım eşiği',
    'sunum.config.entry.b3': 'Üretime hızlı başlangıç',
    'sunum.config.standard.label': 'Standard',
    'sunum.config.standard.tag': 'En çok tercih edilen',
    'sunum.config.standard.desc': 'Dengeli yatırım seviyesi. Üretim, dolum ve paketleme süreçlerinde operasyonel verimlilik.',
    'sunum.config.standard.b1': 'Dengeli otomasyon seviyesi',
    'sunum.config.standard.b2': 'Operasyonel verimlilik',
    'sunum.config.standard.b3': 'Büyüyen operasyonlar için',
    'sunum.config.advanced.label': 'Advanced',
    'sunum.config.advanced.tag': 'Endüstriyel ölçek',
    'sunum.config.advanced.desc': 'Yüksek otomasyon seviyesi. Daha az personel, daha yüksek hız, daha kontrollü üretim.',
    'sunum.config.advanced.b1': 'Tam otomatik konfigürasyon',
    'sunum.config.advanced.b2': 'Daha az personel ihtiyacı',
    'sunum.config.advanced.b3': 'Endüstriyel ölçek üretim',

    'sunum.cta.eyebrow': 'SONRAKİ ADIM',
    'sunum.cta.title1': 'Üretim fikrinizi',
    'sunum.cta.title2': 'uygulanabilir projeye dönüştürelim.',
    'sunum.cta.desc': 'Hedef kapasite, ambalaj formatı ve otomasyon seviyesi netleştikten sonra size özel nihai teklif hazırlanır.',
    'sunum.cta.button': 'Teknik Toplantı Talep Et',
    'sunum.cta.secondary': 'Tüm Çözümleri İncele',
    'sunum.cta.step1': 'Ürün ve ambalaj formatı onayı',
    'sunum.cta.step2': 'Kapasite ve otomasyon seçimi',
    'sunum.cta.step3': 'Yerleşim ve altyapı incelemesi',
    'sunum.cta.step4': 'Nihai ticari teklif',
  },
  en: {
    // Navigation
    'nav.solutions': 'Solutions',
    'nav.readyLines': 'Ready Lines',
    'nav.singleMachines': 'Single Machines',
    'nav.customProjects': 'Custom Projects',
    'nav.services': 'Services',
    'nav.references': 'References',
    'nav.corporate': 'Corporate',
    'nav.blog': 'Blog / Guide',
    'nav.contact': 'Contact',
    
    // Hero
    'hero.label': 'INDUSTRIAL SOLUTIONS',
    'hero.line1': 'Request a Proposal for',
    'hero.line2': 'Your Production Project',
    'hero.description': 'From food production to industry-independent projects, we design and install systems tailored to your needs.',
    'hero.cta': 'Send Project Details',
    'hero.learnMore': 'Explore Solutions',
    'hero.weSupport': 'WE SUPPORT',
    'hero.support.readyLines': 'Ready Production Lines',
    'hero.support.readyLines.desc': 'Tomato paste, sauce, tomato processing lines',
    'hero.support.singleMachines': 'Single Machines',
    'hero.support.singleMachines.desc': 'Dairy process, filling & packaging',
    'hero.support.customProjects': 'Custom Projects',
    'hero.support.customProjects.desc': 'Industry-independent turnkey solutions',
    'hero.support.technical': 'Technical Coordination',
    'hero.support.technical.desc': 'Engineering, installation, commissioning',
    'hero.feature.turnkey': 'Turnkey Coordination',
    'hero.feature.sourcing': 'Flexible Sourcing',
    'hero.feature.multiSector': 'Multi-Sector Expertise',
    'hero.feature.proposals': 'Structured Proposals',
    
    // Hero Slides
    'hero.slide2.label': 'ONLINE CONFIGURATOR',
    'hero.slide2.line1': 'Configure Your',
    'hero.slide2.line2': 'Production Line Online',
    'hero.slide2.description': 'Build your ideal line with our interactive configurator for tomato paste, sauce, dairy and filling systems.',
    'hero.slide2.cta': 'Open Configurator',
    'hero.slide2.secondary': 'Explore Solutions',
    'hero.slide3.label': 'GLOBAL REFERENCES',
    'hero.slide3.line1': 'Production Solutions in',
    'hero.slide3.line2': '30+ Countries',
    'hero.slide3.description': 'Making a difference in the industry with completed projects and trusted partnerships worldwide.',
    'hero.slide3.cta': 'View References',
    'hero.slide3.secondary': 'About Us',
    
    // Quick Cards
    'card.readyLine.title': 'Select Ready Line',
    'card.readyLine.desc': 'Tomato paste, tomato, mayonnaise, ketchup and sauce production lines',
    'card.singleMachine.title': 'Select Single Machine',
    'card.singleMachine.desc': 'Dairy process, filling and packaging machines',
    'card.customProject.title': 'Start Custom Project',
    'card.customProject.desc': 'Industry-independent turnkey solutions',
    
    'process.label': 'PROCESS',
    'process.title': 'How We Work',
    'process.step1': 'Analysis',
    'process.step2': 'Concept',
    'process.step3': 'Procurement',
    'process.step4': 'Installation',
    'process.step5': 'Commissioning',
    'process.step6': 'Growth',
    
    // CTA
    'cta.label': 'GET STARTED',
    'cta.title': 'Describe your project in 2 minutes',
    'cta.subtitle': 'Free preliminary evaluation and technical consultancy',
    'cta.button': 'Quick Quote',
    
    // Solutions
    'solutions.title': 'Our Solutions',
    'solutions.turnkey.title': 'Turnkey Facility Installation',
    'solutions.turnkey.desc': 'Food facilities, dairy products, filling & packaging facilities',
    'solutions.engineering.title': 'Production Line Design & Engineering',
    'solutions.engineering.desc': 'Process design, capacity planning, equipment lists, layout plans',
    'solutions.installation.title': 'Installation, Commissioning & Training',
    'solutions.installation.desc': 'Field coordination, commissioning, operator training',
    
    // Ready Lines
    'readyLines.title': 'Ready Lines',
    'readyLines.tomato.title': 'Tomato Paste & Tomato Processing Lines',
    'readyLines.tomato.desc': 'Modular, scalable production systems',
    'readyLines.sauce.title': 'Mayonnaise, Ketchup & Sauce Production Lines',
    'readyLines.sauce.desc': 'Professional, high-capacity line solutions',
    
    // Single Machines
    'singleMachines.title': 'Single Machines',
    'singleMachines.dairy.title': 'Dairy Process Machines',
    'singleMachines.dairy.desc': 'Homogenizer, separator, pasteurizer and more',
    'singleMachines.filling.title': 'Filling & Packaging Machines',
    'singleMachines.filling.desc': 'Filling, capping, labeling systems',
    
    // Custom Projects
    'customProjects.title': 'Custom Projects',
    'customProjects.hero': 'Not limited by catalog',
    'customProjects.heroDesc': 'We define the project needs and build the working system.',
    
    // Services
    'services.title': 'Our Services',
    'services.engineering': 'Project & Engineering',
    'services.manufacturer': 'Manufacturer Organization',
    'services.tracking': 'Production Tracking & Testing',
    'services.logistics': 'Logistics',
    'services.installation': 'Installation & Commissioning',
    'services.training': 'Training',
    'services.support': 'Technical Support & Spare Parts',
    
    // References
    'references.title': 'Our References',
    'references.food': 'Food Projects',
    'references.dairy': 'Dairy Projects',
    'references.custom': 'Custom Projects',
    
    // Corporate
    'corporate.title': 'Corporate',
    'corporate.about': 'About Us',
    'corporate.vision': 'Vision & Mission',
    'corporate.whyTurkey': 'Why Turkish Manufacturers?',
    'corporate.team': 'Our Team',
    
    // Blog
    'blog.title': 'Blog & Guide',
    
    // Contact
    'contact.title': 'Contact',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Phone',
    'contact.form.company': 'Company Name',
    'contact.form.message': 'Your Message',
    'contact.form.submit': 'Submit',
    'contact.whatsapp': 'Contact via WhatsApp',
    
    // Footer
    'footer.rights': 'All rights reserved.',
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact Information',
    
    // Line Builder
    'lineBuilder.title': 'Build Your Own Filling Line',
    'lineBuilder.subtitle': 'Configure your line based on product type, capacity, and packaging preference.',
    'lineBuilder.step1': 'Product Type',
    'lineBuilder.step2': 'Capacity',
    'lineBuilder.step3': 'Packaging Type',
    'lineBuilder.step4volume': 'Packaging Volume',
    'lineBuilder.step5': 'Line Equipment',
    'lineBuilder.step1.desc': 'Select the type of product to be filled.',
    'lineBuilder.step2.desc': 'Define your hourly production capacity.',
    'lineBuilder.step3.desc': 'Choose the packaging type you will use.',
    'lineBuilder.step4volume.desc': 'Select the volume of the packaging to be filled.',
    'lineBuilder.step5.desc': 'Recommended equipment auto-selected. Add or remove as needed.',
    'lineBuilder.summary': 'Line Summary',
    'lineBuilder.getQuote': 'Request Quote for This Line',
    'lineBuilder.reset': 'Reset',
    'lineBuilder.quote.contactTitle': 'Your Contact Information',
    'lineBuilder.quote.note': 'Additional Notes / Special Requests',
    'lineBuilder.quote.submit': 'Send Quote Request',
    'lineBuilder.quote.sent': 'Quote Request Prepared!',
    'lineBuilder.quote.sentDesc': 'Your email app will open. Send the message to reach our technical office.',
    'lineBuilder.product.liquid': 'Liquid',
    'lineBuilder.product.semiFluid': 'Semi-Fluid',
    'lineBuilder.product.viscous': 'Viscous',
    'lineBuilder.product.powder': 'Powder / Granule',
    'lineBuilder.product.liquid.desc': 'Water, milk, fruit juice',
    'lineBuilder.product.semi-fluid.desc': 'Yogurt, honey, jam',
    'lineBuilder.product.viscous.desc': 'Paste, ketchup, mayonnaise',
    'lineBuilder.product.powder.desc': 'Powder food, spice, granule',
    'lineBuilder.capacity.small': 'Small',
    'lineBuilder.capacity.medium': 'Medium',
    'lineBuilder.capacity.large': 'Large',
    'lineBuilder.capacity.industrial': 'Industrial',
    'lineBuilder.capacity.small.desc': '500–2,000 units/hour',
    'lineBuilder.capacity.medium.desc': '2,000–5,000 units/hour',
    'lineBuilder.capacity.large.desc': '5,000–10,000 units/hour',
    'lineBuilder.capacity.industrial.desc': '10,000+ units/hour',
    'lineBuilder.packaging.glass': 'Glass Bottle',
    'lineBuilder.packaging.pet': 'PET Bottle',
    'lineBuilder.packaging.tin': 'Tin Can',
    'lineBuilder.packaging.pouch': 'Pouch / Doypack',
    'lineBuilder.packaging.jar': 'Jar',
    'lineBuilder.packaging.ibc': 'Drum / IBC',
    'lineBuilder.equipment.filler': 'Filling Machine',
    'lineBuilder.equipment.capper': 'Capper',
    'lineBuilder.equipment.labeler': 'Labeler',
    'lineBuilder.equipment.shrink': 'Shrink Wrapper',
    'lineBuilder.equipment.conveyor': 'Conveyor System',
    'lineBuilder.equipment.uv': 'UV / Sterilization',
    'lineBuilder.equipment.accumulation': 'Accumulation Table',

    // Configurator Slider
    'config.slide1.label': 'CONFIGURATOR',
    'config.slide1.line1': 'Configure Your',
    'config.slide1.line2': 'Production Line Online',
    'config.slide1.description': 'Tomato paste, sauce, dairy process or filling & packaging — build your configuration and get a quote.',
    'config.slide1.cta': 'Start Below',
    'config.slide1.secondary': 'Explore Solutions',
    'config.slide2.label': 'TOMATO & PASTE',
    'config.slide2.line1': 'MACLINE Series',
    'config.slide2.line2': 'Tomato Processing Lines',
    'config.slide2.description': 'Find the best package for you with our Brix calculator and detailed comparison table.',
    'config.slide2.cta': 'Paste Configurator',
    'config.slide2.secondary': 'Ready Lines',
    'config.slide3.label': 'SAUCE & DAIRY',
    'config.slide3.line1': 'Sauce Lines &',
    'config.slide3.line2': 'Dairy Processing Systems',
    'config.slide3.description': 'Configure mayonnaise, ketchup, sauce production lines and dairy processing equipment in one place.',
    'config.slide3.cta': 'Sauce Configurator',
    'config.slide3.secondary': 'Dairy Process',
    'config.support.label': 'CONFIGURATION AREAS',
    'config.support.tomato': 'Tomato & Paste',
    'config.support.tomato.desc': 'MACLINE series tomato processing lines',
    'config.support.sauce': 'Sauce Lines',
    'config.support.sauce.desc': 'Mayonnaise, ketchup & sauce production systems',
    'config.support.dairy': 'Dairy Process',
    'config.support.dairy.desc': 'Pasteurization, homogenization equipment',
    'config.support.filling': 'Filling & Packaging',
    'config.support.filling.desc': 'Interactive line builder for filling lines',

    // Common
    'common.explore': 'Explore',
    'common.learnMore': 'Learn More',
    'common.getQuote': 'Get Quote',
    'common.viewAll': 'View All',
    'common.back': 'Back',
    'common.compare': 'Compare',

    // Sunum / Presentation Landing
    'sunum.nav': 'Presentation',
    'sunum.hero.eyebrow': 'INDUSTRIAL PROJECT DEVELOPMENT',
    'sunum.hero.title1': 'Starting production',
    'sunum.hero.title2': 'is not complicated.',
    'sunum.hero.title3': 'Share your idea;',
    'sunum.hero.title4': 'we build the system.',
    'sunum.hero.desc': 'ProcessTürk is an industrial project development and machinery sourcing brand that transforms production ideas into executable manufacturing systems for international clients.',
    'sunum.hero.cta': 'Describe Your Project',
    'sunum.hero.secondary': 'Service Areas',
    'sunum.hero.tagBadge': 'Türkiye • Africa • Gulf • Middle East',

    'sunum.positioning.eyebrow': 'POSITIONING',
    'sunum.positioning.title': 'More than machinery —',
    'sunum.positioning.titleAccent': 'a working production system.',
    'sunum.positioning.desc': 'Industrial investment is not only about buying machines. It is about building a working production system. Our role is to clarify what needs to be built, which equipment is required and what steps are needed to move from idea to production.',

    'sunum.approach.eyebrow': 'OUR APPROACH',
    'sunum.approach.title': 'From idea to production,',
    'sunum.approach.titleAccent': 'one coordination.',
    'sunum.approach.desc': 'Investors no longer juggle multiple suppliers and engineering parties. ProcessTürk manages the entire process under a single project structure.',
    'sunum.approach.card1.title': 'Technical Configuration',
    'sunum.approach.card1.desc': 'Line design tailored to product, capacity and automation needs.',
    'sunum.approach.card2.title': 'Machinery Sourcing',
    'sunum.approach.card2.desc': 'Comparative procurement from verified manufacturers.',
    'sunum.approach.card3.title': 'Process Planning',
    'sunum.approach.card3.desc': 'End-to-end flow design from raw material to packaging.',
    'sunum.approach.card4.title': 'Installation Coordination',
    'sunum.approach.card4.desc': 'On-site assembly, commissioning and testing oversight.',
    'sunum.approach.card5.title': 'Startup Support',
    'sunum.approach.card5.desc': 'Operator training and production launch coordination.',

    'sunum.process.eyebrow': 'PROCESS FLOW',
    'sunum.process.title': 'A single system,',
    'sunum.process.titleAccent': 'with a defined flow.',
    'sunum.process.step1': 'Raw Material Preparation',
    'sunum.process.step2': 'Mixing & Cooking',
    'sunum.process.step3': 'Holding Tank',
    'sunum.process.step4': 'Filling',
    'sunum.process.step5': 'Capping',
    'sunum.process.step6': 'Labelling',
    'sunum.process.step7': 'Final Packaging',

    'sunum.numbers.eyebrow': 'CAPACITY',
    'sunum.numbers.title': 'Scalable',
    'sunum.numbers.titleAccent': 'production infrastructure.',
    'sunum.numbers.stat1Value': '1,500 kg/h',
    'sunum.numbers.stat1Label': 'Maximum hourly output',
    'sunum.numbers.stat1Desc': 'Configurable capacity depending on recipe, viscosity and filling format.',
    'sunum.numbers.stat2Value': '8–12 weeks',
    'sunum.numbers.stat2Label': 'Typical delivery time',
    'sunum.numbers.stat2Desc': 'Varies based on configuration and manufacturing conditions.',
    'sunum.numbers.stat3Value': '3 levels',
    'sunum.numbers.stat3Label': 'Automation flexibility',
    'sunum.numbers.stat3Desc': 'Entry, Standard and Advanced configurations available.',

    'sunum.services.eyebrow': 'SERVICE AREAS',
    'sunum.services.title': 'Industrial scope,',
    'sunum.services.titleAccent': 'sector independent.',
    'sunum.services.coreLabel': 'Core Industrial Areas',
    'sunum.services.additionalLabel': 'Additional Project Areas',
    'sunum.services.core1': 'Sauce, Mayonnaise & Ketchup Lines',
    'sunum.services.core2': 'Tomato Paste Processing',
    'sunum.services.core3': 'Dairy Processing Lines',
    'sunum.services.core4': 'Filling & Packaging Systems',
    'sunum.services.core5': 'Cold Storage Solutions',
    'sunum.services.core6': 'Turnkey Food Processing Plants',
    'sunum.services.core7': 'Custom Industrial Projects',
    'sunum.services.add1': 'Honey Processing Plant',
    'sunum.services.add2': 'Bouillon Production Plant',
    'sunum.services.add3': 'Salt Processing & Packaging',
    'sunum.services.add4': 'Cube Sugar Production Plant',
    'sunum.services.add5': 'Poultry Egg Production Facility',
    'sunum.services.add6': 'Soap, Detergent & Bleach Plant',
    'sunum.services.add7': 'Plastic Recycling Lines',
    'sunum.services.add8': 'Construction Material Plants',

    'sunum.value.eyebrow': 'WHY PROCESSTÜRK',
    'sunum.value.title': 'Technical accuracy,',
    'sunum.value.titleAccent': 'commercial practicality.',
    'sunum.value.card1.title': 'Single-Point Coordination',
    'sunum.value.card1.desc': 'No more dealing with multiple manufacturers and technical parties separately.',
    'sunum.value.card2.title': 'Executable Approach',
    'sunum.value.card2.desc': 'Not just a product list — a working production system that runs.',
    'sunum.value.card3.title': 'Budget-Aligned Configuration',
    'sunum.value.card3.desc': 'Entry, Standard or Advanced — level matched to your investment budget.',
    'sunum.value.card4.title': 'International Experience',
    'sunum.value.card4.desc': 'Project experience across Türkiye, Africa, Gulf and Middle East.',
    'sunum.value.card5.title': 'Technical + Commercial Lens',
    'sunum.value.card5.desc': 'Engineering plus return logic, operational ease and commercial viability.',
    'sunum.value.card6.title': 'Scalable System',
    'sunum.value.card6.desc': 'Start small and grow capacity or automation level in later phases.',

    'sunum.config.eyebrow': 'CONFIGURATION LEVELS',
    'sunum.config.title': 'Right equipment,',
    'sunum.config.titleAccent': 'right investment.',
    'sunum.config.entry.label': 'Entry',
    'sunum.config.entry.tag': 'Starter',
    'sunum.config.entry.desc': 'Lower-investment, semi-automatic solution. Core production functions are covered.',
    'sunum.config.entry.b1': 'Semi-automatic configuration',
    'sunum.config.entry.b2': 'Lower investment threshold',
    'sunum.config.entry.b3': 'Fast production start',
    'sunum.config.standard.label': 'Standard',
    'sunum.config.standard.tag': 'Most chosen',
    'sunum.config.standard.desc': 'Balanced investment level. Operational efficiency across production, filling and packaging.',
    'sunum.config.standard.b1': 'Balanced automation level',
    'sunum.config.standard.b2': 'Operational efficiency',
    'sunum.config.standard.b3': 'For growing operations',
    'sunum.config.advanced.label': 'Advanced',
    'sunum.config.advanced.tag': 'Industrial scale',
    'sunum.config.advanced.desc': 'High automation level. Fewer operators, higher speed, more controlled production.',
    'sunum.config.advanced.b1': 'Fully automatic configuration',
    'sunum.config.advanced.b2': 'Reduced operator dependency',
    'sunum.config.advanced.b3': 'Industrial-scale production',

    'sunum.cta.eyebrow': 'NEXT STEP',
    'sunum.cta.title1': 'Let’s turn your production idea',
    'sunum.cta.title2': 'into an executable project.',
    'sunum.cta.desc': 'Once target capacity, packaging format and automation level are confirmed, your final tailored offer can be prepared.',
    'sunum.cta.button': 'Request a Technical Meeting',
    'sunum.cta.secondary': 'Explore All Solutions',
    'sunum.cta.step1': 'Product and packaging format confirmation',
    'sunum.cta.step2': 'Capacity and automation selection',
    'sunum.cta.step3': 'Layout and utility review',
    'sunum.cta.step4': 'Final commercial offer',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('tr');

  const t = useCallback(
    (key: string): string => {
      return translations[language][key] || key;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
